/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModerationsRequest
 */
export interface ModerationsRequest {
    /**
     * 
     * @type {string}
     * @memberof ModerationsRequest
     */
    prompt: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModerationsRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ModerationsRequest
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof ModerationsRequest
     */
    responseLanguage?: string;
}

/**
 * Check if a given object implements the ModerationsRequest interface.
 */
export function instanceOfModerationsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prompt" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ModerationsRequestFromJSON(json: any): ModerationsRequest {
    return ModerationsRequestFromJSONTyped(json, false);
}

export function ModerationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModerationsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'userId': json['user_id'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'responseLanguage': !exists(json, 'response_language') ? undefined : json['response_language'],
    };
}

export function ModerationsRequestToJSON(value?: ModerationsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompt': value.prompt,
        'user_id': value.userId,
        'model': value.model,
        'response_language': value.responseLanguage,
    };
}

