/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestionsRequest
 */
export interface SuggestionsRequest {
    /**
     * 
     * @type {string}
     * @memberof SuggestionsRequest
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof SuggestionsRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the SuggestionsRequest interface.
 */
export function instanceOfSuggestionsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prompt" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function SuggestionsRequestFromJSON(json: any): SuggestionsRequest {
    return SuggestionsRequestFromJSONTyped(json, false);
}

export function SuggestionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'userId': json['user_id'],
    };
}

export function SuggestionsRequestToJSON(value?: SuggestionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompt': value.prompt,
        'user_id': value.userId,
    };
}

