/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeLineRequest
 */
export interface TimeLineRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeLineRequest
     */
    prompts: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TimeLineRequest
     */
    index?: Array<number>;
}

/**
 * Check if a given object implements the TimeLineRequest interface.
 */
export function instanceOfTimeLineRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prompts" in value;

    return isInstance;
}

export function TimeLineRequestFromJSON(json: any): TimeLineRequest {
    return TimeLineRequestFromJSONTyped(json, false);
}

export function TimeLineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeLineRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prompts': json['prompts'],
        'index': !exists(json, 'index') ? undefined : json['index'],
    };
}

export function TimeLineRequestToJSON(value?: TimeLineRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompts': value.prompts,
        'index': value.index,
    };
}

